Task 1:

Import the numpy library and check its version.

In [1]:
import numpy as np

In [3]:
np.__version__

'2.5.2'

Task 2:

Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].

Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.

Generate an array of 10 evenly spaced values between 0 and 5.

In [5]:
ID_array = np.array([1, 2, 3, 4, 5])
ID_array

array([1, 2, 3, 4, 5])

In [9]:
ID_array.ndim

1

In [17]:
IID_arrary= np.random.randint(1, 9, size=(3,3))
IID_arrary

array([[5, 8, 1],
       [7, 1, 4],
       [5, 2, 7]], dtype=int32)

In [18]:
IID_arrary.ndim

2

In [13]:
even_space= np.linspace(0, 5, 10)
even_space

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Indexing and Slicing Arrays:
Indexing and slicing allow you to access and modify specific elements of an array.

Task 3:

Access the element in the second row, third column of the 2D array you created above.

Slice the first two rows and the first two columns from the same array.

Modify the value in the last row and first column to 100.

In [20]:
#Accessing element
IID_arrary[1,2]

np.int32(4)

In [22]:
IID_arrary[0:2, 0:2]

array([[5, 8],
       [7, 1]], dtype=int32)

In [23]:
IID_arrary[2,0] = 100
print(IID_arrary)

[[  5   8   1]
 [  7   1   4]
 [100   2   7]]


Properties and Methods of NumPy Arrays
NumPy arrays have several useful properties and methods.

Task 4:

Find the shape, size, and data type of the 2D array.

Change the 1D array into a 2D array of shape (5,1).

Flatten a multi-dimensional array back into a 1D array.

In [27]:
print("The shape of array is ", IID_arrary.shape)
print("The size of array is ", IID_arrary.size)
print("The data type of array is ", IID_arrary.dtype)

The shape of array is  (3, 3)
The size of array is  9
The data type of array is  int32


In [30]:
new_arr = ID_array.reshape(5,1)
new_arr.ndim

2

In [31]:
new_arr.flatten()

array([1, 2, 3, 4, 5])

Operations on NumPy Arrays
Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

Task 5:

Add 5 to every element in the 1D array.

Multiply the 2D array by 3.

Perform matrix multiplication between the following two arrays:

A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

In [33]:
addition = ID_array + 5
addition

array([ 6,  7,  8,  9, 10])

In [35]:
mul = IID_arrary * 3
mul

array([[ 15,  24,   3],
       [ 21,   3,  12],
       [300,   6,  21]], dtype=int32)

In [38]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_mul = np.dot(A, B)
print(matrix_mul)

[[19 22]
 [43 50]]


Understanding Broadcasting
Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

Task 6:

Create a 3x3 matrix of ones and a 1D array of length 3.

Add the 1D array to each row of the matrix using broadcasting.

In [43]:
x = np.ones(shape= (3,3))
y = np.random.randint(1, 11, size= 3)
print(x)
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[10  1  3]


In [44]:
x + y

array([[11.,  2.,  4.],
       [11.,  2.,  4.],
       [11.,  2.,  4.]])