In [1]:
import numpy as np

In [2]:
np.__version__

'2.5.2'

Creating Numpy Array   

In [3]:
list1 = [1,2,3,4,5,8,9]

arry1= np.array(list1)

In [4]:
type(arry1)

numpy.ndarray

In [5]:
arry1

array([1, 2, 3, 4, 5, 8, 9])

In [6]:
arry1.ndim

1

In [7]:
arry1.shape

(7,)

In [8]:
list2 = [
    [1,2,3], 
    [4,5,6], 
    [7,8,9]]

arry2 = np.array(list2)

In [9]:
arry2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arry2.shape

(3, 3)

In [11]:
arry2.ndim

2

In [14]:
list3 = [
    [[1,2,3], 
    [4,5,6], 
    [7,8,9]],

    [[2,5,9],
     [3,6,7],
     [1,4,8]],

     [[1,5,9],
      [2,6,7],
      [3,4,8]]
      ]

arry3 = np.array(list3)

In [15]:
arry3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 5, 9],
        [3, 6, 7],
        [1, 4, 8]],

       [[1, 5, 9],
        [2, 6, 7],
        [3, 4, 8]]])

In [16]:
arry3.shape

(3, 3, 3)

In [17]:
arry3.ndim

3

In [24]:
list4 = [
    [[1,2,3], 
    [4,5,6], 
    [7,8,9]],

    [[2,5,9],
     [3,6,7],
     [1,4,8]]
      ]

arry4 = np.array(list4)

In [21]:
arry4.shape

(2, 3, 3)

In [22]:
arry4.ndim  

3

In [29]:
np.zeros(shape = (2,3,6), dtype= int)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [34]:
np.ones(shape = (2, 3, 5, 5), dtype = int)

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

In [35]:
np.full(shape = (3,4), fill_value = 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [40]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.linspace((0,1,2), (30,20,60), num= 5)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])